version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    networks:
      - image-bbox-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - image-bbox-network

  database:
    image: postgres:13
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    networks:
      - image-bbox-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: serve -d build -p 3000
    networks:
      - image-bbox-network

networks:
  image-bbox-network:
    driver: bridge
